#spring:
#  mvc:
#    static-path-pattern: /static/**
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

    druid:
      filters: wall,stat,slf4j
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 123456
        reset-enable: false

      web-stat-filter:
        enabled: true
        url-pattern: /*
      aop-patterns: com.boot.springbootweb.*

      filter:
        stat:
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true
        wall:
          enabled: true


#    type: com.zaxxer.hikari.HikariDataSource
#server:
#  error:
#    path: /error